#!/bin/bash
# Shell wrapper
command -v curl > /dev/null || echo "curl Command doesn't exist. Please install curl before running shw" || exit 1

BIN_PATH=~/.shw/bin
URL=""

while [[ $# -gt 0 ]]; do
  case $1 in
  -b | --binpath)
    BIN_PATH="$2"
    shift
    shift
    ;;
  -f | --filename)
    FILE="$2"
    shift
    shift
    ;;
  *)
    if [ -z $URL ]; then
      URL=("$1")
    fi
    shift
    break
    ;;
  esac
done

if [ -z $FILE ]; then
  if ! [ -z $URL ]; then
    FILE=${URL##*/}

  else
    exit 1
  fi
fi

FILE=$BIN_PATH/$FILE

if ! [ -d $BIN_PATH ]; then
 mkdir -p $BIN_PATH
fi

if ! [ -x $FILE ]; then
  curl -XGET -Ls $URL --output $FILE
  chmod +x $FILE
fi

# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
  cd "$(dirname "$0")" || exit 1
fi
exec "$FILE" "$@"
